/**
 * Mock 데이터 파일
 * - CHAMPIONS: 챔피언 목록 (id는 Riot Data Dragon 이미지 키와 동일하게 맞춰둠)
 * - AUGMENTS: 증강 목록 (tier: 'silver' | 'gold' | 'prism')
 * - DDRAGON_VERSION: Data Dragon 패치 버전 (이미지가 깨지면 이 값을 최신 버전으로 바꿔주세요)
 *
 * 실제 서비스 붙일 때는 이 파일을 fetch('/api/champions') 등으로 교체하면 됩니다.
 */

window.DDRAGON_VERSION = "16.17.1";

// Data Dragon 챔피언 정사각형 아이콘 URL 생성기
window.getChampionImageUrl = function (championId) {
  return `https://ddragon.leagueoflegends.com/cdn/${window.DDRAGON_VERSION}/img/champion/${championId}.png`;
};

// 증강 카드 배경/프레임: 실제 게임(아레나/아수라장)에서 쓰는 CommunityDragon 공식 에셋
const CDRAGON_CARD_BASE = "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/augmentselection";
window.AUGMENT_CARD_BG_URL = `${CDRAGON_CARD_BASE}/augmentcard_bg.png`;
window.AUGMENT_CARD_FRAME_URLS = {
  silver: `${CDRAGON_CARD_BASE}/augmentcard_frame_silver.png`,
  gold: `${CDRAGON_CARD_BASE}/augmentcard_frame_gold.png`,
  prism: `${CDRAGON_CARD_BASE}/augmentcard_frame_prismatic.png`,
};

window.CHAMPIONS = [
  { id: "Aatrox", name: "아트록스", role: "전사" },
  { id: "Ahri", name: "아리", role: "마법사" },
  { id: "Akali", name: "아칼리", role: "암살자" },
  { id: "Akshan", name: "아크샨", role: "원거리 딜러" },
  { id: "Alistar", name: "알리스타", role: "탱커" },
  { id: "Ambessa", name: "암베사", role: "전사" },
  { id: "Amumu", name: "아무무", role: "탱커" },
  { id: "Anivia", name: "애니비아", role: "마법사" },
  { id: "Annie", name: "애니", role: "마법사" },
  { id: "Aphelios", name: "아펠리오스", role: "원거리 딜러" },
  { id: "Ashe", name: "애쉬", role: "원거리 딜러" },
  { id: "AurelionSol", name: "아우렐리온 솔", role: "마법사" },
  { id: "Aurora", name: "오로라", role: "마법사" },
  { id: "Azir", name: "아지르", role: "마법사" },
  { id: "Bard", name: "바드", role: "서포터" },
  { id: "Belveth", name: "벨베스", role: "전사" },
  { id: "Blitzcrank", name: "블리츠크랭크", role: "탱커" },
  { id: "Brand", name: "브랜드", role: "마법사" },
  { id: "Braum", name: "브라움", role: "탱커" },
  { id: "Briar", name: "브라이어", role: "전사" },
  { id: "Caitlyn", name: "케이틀린", role: "원거리 딜러" },
  { id: "Camille", name: "카밀", role: "전사" },
  { id: "Cassiopeia", name: "카시오페아", role: "마법사" },
  { id: "Chogath", name: "초가스", role: "탱커" },
  { id: "Corki", name: "코르키", role: "원거리 딜러" },
  { id: "Darius", name: "다리우스", role: "전사" },
  { id: "Diana", name: "다이애나", role: "전사" },
  { id: "DrMundo", name: "문도 박사", role: "탱커" },
  { id: "Draven", name: "드레이븐", role: "원거리 딜러" },
  { id: "Ekko", name: "에코", role: "암살자" },
  { id: "Elise", name: "엘리스", role: "암살자" },
  { id: "Evelynn", name: "이블린", role: "암살자" },
  { id: "Ezreal", name: "이즈리얼", role: "원거리 딜러" },
  { id: "Fiddlesticks", name: "피들스틱", role: "마법사" },
  { id: "Fiora", name: "피오라", role: "전사" },
  { id: "Fizz", name: "피즈", role: "암살자" },
  { id: "Galio", name: "갈리오", role: "탱커" },
  { id: "Gangplank", name: "갱플랭크", role: "전사" },
  { id: "Garen", name: "가렌", role: "전사" },
  { id: "Gnar", name: "나르", role: "전사" },
  { id: "Gragas", name: "그라가스", role: "전사" },
  { id: "Graves", name: "그레이브즈", role: "원거리 딜러" },
  { id: "Gwen", name: "그웬", role: "전사" },
  { id: "Hecarim", name: "헤카림", role: "전사" },
  { id: "Heimerdinger", name: "하이머딩거", role: "마법사" },
  { id: "Hwei", name: "흐웨이", role: "마법사" },
  { id: "Illaoi", name: "일라오이", role: "전사" },
  { id: "Irelia", name: "이렐리아", role: "전사" },
  { id: "Ivern", name: "아이번", role: "서포터" },
  { id: "Janna", name: "잔나", role: "서포터" },
  { id: "JarvanIV", name: "자르반 4세", role: "전사" },
  { id: "Jax", name: "잭스", role: "전사" },
  { id: "Jayce", name: "제이스", role: "전사" },
  { id: "Jhin", name: "진", role: "원거리 딜러" },
  { id: "Jinx", name: "징크스", role: "원거리 딜러" },
  { id: "KSante", name: "크산테", role: "탱커" },
  { id: "Kaisa", name: "카이사", role: "원거리 딜러" },
  { id: "Kalista", name: "칼리스타", role: "원거리 딜러" },
  { id: "Karma", name: "카르마", role: "마법사" },
  { id: "Karthus", name: "카서스", role: "마법사" },
  { id: "Kassadin", name: "카사딘", role: "암살자" },
  { id: "Katarina", name: "카타리나", role: "암살자" },
  { id: "Kayle", name: "케일", role: "원거리 딜러" },
  { id: "Kayn", name: "케인", role: "전사" },
  { id: "Kennen", name: "케넨", role: "마법사" },
  { id: "Khazix", name: "카직스", role: "암살자" },
  { id: "Kindred", name: "킨드레드", role: "원거리 딜러" },
  { id: "Kled", name: "클레드", role: "전사" },
  { id: "KogMaw", name: "코그모", role: "원거리 딜러" },
  { id: "Leblanc", name: "르블랑", role: "암살자" },
  { id: "LeeSin", name: "리 신", role: "전사" },
  { id: "Leona", name: "레오나", role: "탱커" },
  { id: "Lillia", name: "릴리아", role: "전사" },
  { id: "Lissandra", name: "리산드라", role: "마법사" },
  { id: "Locke", name: "로크", role: "암살자" },
  { id: "Lucian", name: "루시안", role: "원거리 딜러" },
  { id: "Lulu", name: "룰루", role: "서포터" },
  { id: "Lux", name: "럭스", role: "마법사" },
  { id: "Malphite", name: "말파이트", role: "탱커" },
  { id: "Malzahar", name: "말자하", role: "마법사" },
  { id: "Maokai", name: "마오카이", role: "탱커" },
  { id: "MasterYi", name: "마스터 이", role: "전사" },
  { id: "Mel", name: "멜", role: "마법사" },
  { id: "Milio", name: "밀리오", role: "서포터" },
  { id: "MissFortune", name: "미스 포츈", role: "원거리 딜러" },
  { id: "MonkeyKing", name: "오공", role: "전사" },
  { id: "Mordekaiser", name: "모데카이저", role: "전사" },
  { id: "Morgana", name: "모르가나", role: "서포터" },
  { id: "Naafiri", name: "나피리", role: "암살자" },
  { id: "Nami", name: "나미", role: "서포터" },
  { id: "Nasus", name: "나서스", role: "전사" },
  { id: "Nautilus", name: "노틸러스", role: "탱커" },
  { id: "Neeko", name: "니코", role: "마법사" },
  { id: "Nidalee", name: "니달리", role: "암살자" },
  { id: "Nilah", name: "닐라", role: "전사" },
  { id: "Nocturne", name: "녹턴", role: "전사" },
  { id: "Nunu", name: "누누와 윌럼프", role: "탱커" },
  { id: "Olaf", name: "올라프", role: "전사" },
  { id: "Orianna", name: "오리아나", role: "마법사" },
  { id: "Ornn", name: "오른", role: "탱커" },
  { id: "Pantheon", name: "판테온", role: "전사" },
  { id: "Poppy", name: "뽀삐", role: "탱커" },
  { id: "Pyke", name: "파이크", role: "서포터" },
  { id: "Qiyana", name: "키아나", role: "암살자" },
  { id: "Quinn", name: "퀸", role: "원거리 딜러" },
  { id: "Rakan", name: "라칸", role: "서포터" },
  { id: "Rammus", name: "람머스", role: "탱커" },
  { id: "RekSai", name: "렉사이", role: "전사" },
  { id: "Rell", name: "렐", role: "탱커" },
  { id: "Renata", name: "레나타 글라스크", role: "서포터" },
  { id: "Renekton", name: "레넥톤", role: "전사" },
  { id: "Rengar", name: "렝가", role: "암살자" },
  { id: "Riven", name: "리븐", role: "전사" },
  { id: "Rumble", name: "럼블", role: "전사" },
  { id: "Ryze", name: "라이즈", role: "마법사" },
  { id: "Samira", name: "사미라", role: "원거리 딜러" },
  { id: "Sejuani", name: "세주아니", role: "탱커" },
  { id: "Senna", name: "세나", role: "서포터" },
  { id: "Seraphine", name: "세라핀", role: "서포터" },
  { id: "Sett", name: "세트", role: "전사" },
  { id: "Shaco", name: "샤코", role: "암살자" },
  { id: "Shen", name: "쉔", role: "탱커" },
  { id: "Shyvana", name: "쉬바나", role: "전사" },
  { id: "Singed", name: "신지드", role: "탱커" },
  { id: "Sion", name: "사이온", role: "탱커" },
  { id: "Sivir", name: "시비르", role: "원거리 딜러" },
  { id: "Skarner", name: "스카너", role: "탱커" },
  { id: "Smolder", name: "스몰더", role: "원거리 딜러" },
  { id: "Sona", name: "소나", role: "서포터" },
  { id: "Soraka", name: "소라카", role: "서포터" },
  { id: "Swain", name: "스웨인", role: "마법사" },
  { id: "Sylas", name: "사일러스", role: "마법사" },
  { id: "Syndra", name: "신드라", role: "마법사" },
  { id: "TahmKench", name: "탐 켄치", role: "탱커" },
  { id: "Taliyah", name: "탈리야", role: "마법사" },
  { id: "Talon", name: "탈론", role: "암살자" },
  { id: "Taric", name: "타릭", role: "서포터" },
  { id: "Teemo", name: "티모", role: "원거리 딜러" },
  { id: "Thresh", name: "쓰레쉬", role: "서포터" },
  { id: "Tristana", name: "트리스타나", role: "원거리 딜러" },
  { id: "Trundle", name: "트런들", role: "전사" },
  { id: "Tryndamere", name: "트린다미어", role: "전사" },
  { id: "TwistedFate", name: "트위스티드 페이트", role: "마법사" },
  { id: "Twitch", name: "트위치", role: "원거리 딜러" },
  { id: "Udyr", name: "우디르", role: "전사" },
  { id: "Urgot", name: "우르곳", role: "전사" },
  { id: "Varus", name: "바루스", role: "원거리 딜러" },
  { id: "Vayne", name: "베인", role: "원거리 딜러" },
  { id: "Veigar", name: "베이가", role: "마법사" },
  { id: "Velkoz", name: "벨코즈", role: "마법사" },
  { id: "Vex", name: "벡스", role: "마법사" },
  { id: "Vi", name: "바이", role: "전사" },
  { id: "Viego", name: "비에고", role: "전사" },
  { id: "Viktor", name: "빅토르", role: "마법사" },
  { id: "Vladimir", name: "블라디미르", role: "마법사" },
  { id: "Volibear", name: "볼리베어", role: "전사" },
  { id: "Warwick", name: "워윅", role: "전사" },
  { id: "Xayah", name: "자야", role: "원거리 딜러" },
  { id: "Xerath", name: "제라스", role: "마법사" },
  { id: "XinZhao", name: "신 짜오", role: "전사" },
  { id: "Yasuo", name: "야스오", role: "전사" },
  { id: "Yone", name: "요네", role: "전사" },
  { id: "Yorick", name: "요릭", role: "전사" },
  { id: "Yunara", name: "유나라", role: "원거리 딜러" },
  { id: "Yuumi", name: "유미", role: "서포터" },
  { id: "Zaahen", name: "자헨", role: "전사" },
  { id: "Zac", name: "자크", role: "탱커" },
  { id: "Zed", name: "제드", role: "암살자" },
  { id: "Zeri", name: "제리", role: "원거리 딜러" },
  { id: "Ziggs", name: "직스", role: "마법사" },
  { id: "Zilean", name: "질리언", role: "서포터" },
  { id: "Zoe", name: "조이", role: "마법사" },
  { id: "Zyra", name: "자이라", role: "마법사" },
];

/**
 * 아래 증강 이름/등급은 실제 '무작위 총력전: 아수라장(아레나)' 모드에 등장하는 증강을 참고했습니다.
 * iconUrl은 CommunityDragon(raw.communitydragon.org)이 제공하는 라이엇 공식 게임 에셋 경로예요.
 * (효과 설명은 게임 내 수치를 간략화해 직접 요약한 것으로, 실제 최신 수치와는 다를 수 있어요)
 * 참고: 리그오브레전드 인벤 가이드 26.11 패치 (namu.wiki, inven.co.kr), CommunityDragon cherry-augments.json
 */
const CDRAGON_ICON_CHERRY = "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons";
const CDRAGON_ICON_KIWI = "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons";

window.AUGMENTS = [
  // ── 실버 (Silver) ── 기본적인 스탯형 증강
  { id: "s01", tier: "silver", icon: "👊", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/heavyhitter_small.png", name: "강타자", desc: "기본 공격 시 최대 체력의 3.5%에 해당하는 추가 물리 피해를 입힙니다." },
  { id: "s02", tier: "silver", icon: "⚡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/zealot_small.png", name: "광신자", desc: "치명타 확률을, 공격 속도를 얻습니다." },
  { id: "s03", tier: "silver", icon: "🏹", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/deft_small.png", name: "능수능란", desc: "60%의 공격 속도를 얻습니다." },
  { id: "s04", tier: "silver", icon: "🏃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/escapeplan_small.png", name: "도주 계획", desc: "체력이 %가 되면 막대한 보호막, 이동 속도, 축소 효과를 얻습니다." },
  { id: "s05", tier: "silver", icon: "🩸", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/goredrink_small.png", name: "선혈포식", desc: "모든 피해 흡혈 15%를 얻습니다." },
  { id: "s06", tier: "silver", icon: "🧙", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/puristcaster_small.png", name: "순수주의자-마법사", desc: "백분율 기반 재사용 대기시간 감소를 얻고 모든 공격 속도를 스킬 가속으로 전환합니다." },
  { id: "s07", tier: "silver", icon: "💪", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/bluntforce_small.png", name: "육중한 힘", desc: "공격력이 10% 증가합니다." },
  { id: "s08", tier: "silver", icon: "🔮", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/adapt_small.png", name: "적응형 능력치", desc: "추가 공격력을 주문력으로 전환합니다. 주문력이 15% 증가합니다." },
  { id: "s09", tier: "silver", icon: "⏳", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradezh_small.png", name: "존야 업그레이드", desc: "존야의 모래시계 재사용 대기시간이 감소합니다. 이제 존야의 모래시계, 추적자의 팔목 보호대 또는 우글렛의 마녀모자로 경직 상태에서 이동할 수 있으며 이동 속도가 증가합니다." },
  { id: "s10", tier: "silver", icon: "🪙", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradecollector_small.png", name: "징수의 총 업그레이드", desc: "징수의 총 기본 지속 효과로 적을 처형하면 처형 기준치가 높아지며 추가 골드를 얻습니다." },
  { id: "s12", tier: "silver", icon: "🔰", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/ultimateunstoppable_small.png", name: "궁극의 저지 불가", desc: "궁극기 사용 시 2초 동안 군중 제어 효과에 면역이 됩니다. (재사용 대기시간 8초)" },
  { id: "s13", tier: "silver", icon: "💨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/shadowrunner_small.png", name: "그림자 질주", desc: "돌진, 도약, 점멸, 순간이동 스킬을 사용하거나 투명 상태에서 벗어난 후 2초 동안 이동 속도가 200 증가합니다." },
  { id: "s14", tier: "silver", icon: "🧪", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/juiced_small.png", name: "도취", desc: "적중 시 마나를 소모해 추가 마법 피해를 입힙니다." },
  { id: "s15", tier: "silver", icon: "🔩", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/infernalsoul_small.png", name: "마법공학의 영혼", desc: "주기적으로 스킬 또는 기본 공격으로 피해를 입히면 번개를 발사해 적에게 연쇄적으로 피해를 입히고 둔화시킵니다." },
  { id: "s16", tier: "silver", icon: "🗡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/escapade_small.png", name: "마법사 (물리)", desc: "주문력을 추가 공격력으로 전환합니다. 공격력이 15% 증가합니다." },
  { id: "s17", tier: "silver", icon: "🏇", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/homeguard_small.png", name: "민병대", desc: "이동 속도가 70% 증가합니다. 피해를 입은 후 3초 동안은 효과가 멈춥니다." },
  { id: "s18", tier: "silver", icon: "🕯️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradeimmolate_small.png", name: "불사르기 업그레이드", desc: "공허한 광휘 및 태양불꽃 방패가 불사르기 효과가 적용된 대상 수에 비례하여 골드를 제공합니다." },
  { id: "s19", tier: "silver", icon: "🌑", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/witchfulthinking_small.png", name: "사악한 정신", desc: "주문력이 60 증가합니다." },
  { id: "s21", tier: "silver", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/slaparound_small.png", name: "우당탕탕", desc: "적을 이동 불가 상태로 만들거나 이동 스킬을 사용할 수 없게 하면 해당 라운드에 15의 적응형 능력치를 얻습니다." },
  { id: "s22", tier: "silver", icon: "💚", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/firstaidkit_small.png", name: "응급처치 키트", desc: "체력 회복 및 보호막 효과가 20% 증가합니다." },
  { id: "s23", tier: "silver", icon: "😈", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/guiltypleasure_small.png", name: "죄책감의 쾌락", desc: "적 챔피언을 이동 불가 상태로 만들거나 이동 스킬을 사용할 수 없게 하면 체력을 회복합니다." },
  { id: "s24", tier: "silver", icon: "👻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/infernalsoul_small.png", name: "지옥불 영혼", desc: "스킬 또는 기본 공격으로 적을 공격할 때마다 추가 피해를 입히는 화염의 드래곤 영혼을 얻습니다." },
  { id: "s25", tier: "silver", icon: "❄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/icecold_small.png", name: "차가운 냉기", desc: "둔화 효과가 이동 속도를 추가로 감소시킵니다." },
  { id: "s26", tier: "silver", icon: "🌪️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/typhoon_small.png", name: "태풍", desc: "기본 공격 시 추가 대상에게 화살을 발사해 감소된 피해를 입히고 적중 시 효과를 적용합니다." },
  { id: "s27", tier: "silver", icon: "🎲", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/tankitorleaveit_small.png", name: "확률적 방어", desc: "공격당할 때 치명타 확률(최대 50%)에 따라 치명 방어가 발동해 받는 피해가 감소할 수 있습니다." },
  { id: "s28", tier: "silver", icon: "🧱", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/adamant_small.png", name: "단호함", desc: "적을 이동 불가 상태로 만들거나 이동 스킬을 사용할 수 없게 할 때마다 방어력 및 마법 저항력을 얻습니다." },
  { id: "s29", tier: "silver", icon: "🛟", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/swiftandsafe_small.png", name: "빠르고 안전하게", desc: "돌진하거나 점멸한 후에 잠시 동안 보호막을 얻습니다. (재사용 대기시간 있음)" },
  { id: "s30", tier: "silver", icon: "👤", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/frostwraith_small.png", name: "서리 망령", desc: "자동 사용, 6.5초마다 주변 적을 1.25초 동안 속박합니다." },
  { id: "s32", tier: "silver", icon: "⚙️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/weightedpopoffs_small.png", name: "중량 폭주", desc: "스킬로 적을 타격하면 폭주 중첩을 얻어 기본 스킬 재사용 대기시간이 감소합니다." },
  { id: "s33", tier: "silver", icon: "🏎️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/critncast_small.png", name: "치명적 가속", desc: "치명타 확률에 해당하는 스킬 가속을 얻습니다." },
  { id: "s34", tier: "silver", icon: "🦵", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/legday_small.png", name: "하체 운동의 날", desc: "10의 이동 속도와 15%의 둔화 저항을 얻습니다." },

  { id: "s35", tier: "silver", icon: "💃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradedeathdance_small.png", name: "죽음의 무도 업그레이드", desc: "골드를 획득합니다. 자신이 받은 피해의 일부만큼을 일정 시간에 걸쳐서 입습니다." },
  { id: "s36", tier: "silver", icon: "🦖", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/stackosaurusrex_small.png", name: "다단 중첩", desc: "스킬 중첩을 영구적으로 획득할 때마다 75% 더 획득합니다!" },
  { id: "s37", tier: "silver", icon: "🔨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/forgedbythemaster_small.png", name: "장인의 솜씨", desc: "아이템 및 증강으로 입히는 피해량이 증가합니다." },
  { id: "s38", tier: "silver", icon: "🔥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/twinfire_small.png", name: "쌍둥이 불꽃", desc: "스킬 피해를 입히면 투사체를 발사해 추가 마법 피해를 입힙니다." },
  { id: "s39", tier: "silver", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/spintowin_small.png", name: "승리를 위한 회전", desc: "회전 스킬의 피해량이 15%, 스킬 가속이 15 증가합니다!" },
  { id: "s40", tier: "silver", icon: "🌊", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/oceansoul_small.png", name: "바다의 영혼", desc: "적에게 피해를 입힌 후 높은 체력 및 마나 재생 효과를 얻는 바다의 영혼을 획득합니다." },
  { id: "s41", tier: "silver", icon: "🪨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/erosion_small.png", name: "부식", desc: "적에게 피해를 입히면 4초 동안 방어력 및 마법 저항력 감소 중첩을 얻습니다." },
  { id: "s42", tier: "silver", icon: "🧘", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "확고한 의지로", desc: "스킬로 적 챔피언에게 피해를 입히면 방어력 및 마법 저항력이 증가합니다." },
  { id: "s43", tier: "silver", icon: "🔄", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/mindtomatter_small.png", name: "정신 변환", desc: "최대 체력이 마나의 절반만큼 증가합니다." },
  { id: "s44", tier: "silver", icon: "👁️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dontblink_small.png", name: "속전속결", desc: "대상보다 이동 속도가 10 높을 때마다 추가 피해량이 1% 증가합니다." },
  { id: "s45", tier: "silver", icon: "📺", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/dontchangethechannel_small.png", name: "채널 고정", desc: "정신 집중 시 매초 보호막을 얻습니다." },
  { id: "s46", tier: "silver", icon: "💨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/sonicboom_small.png", name: "음속 폭발", desc: "아군에게 이로운 효과, 회복, 보호막을 부여하면 아군 주변 적들에게 피해를 입히고 둔화시킵니다." },
  { id: "s47", tier: "silver", icon: "🩸", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "흡수", desc: "피들스틱이 적의 생명을 흡수하여 지속적으로 피해를 입히고 자신을 치료합니다." },
  { id: "s48", tier: "silver", icon: "🔭", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/scopedweapons_small.png", name: "조준경 부착", desc: "공격 사거리가 증가합니다." },
  { id: "s49", tier: "silver", icon: "🪂", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/divebomber_small.png", name: "폭격기", desc: "라운드마다 처음으로 사망하는 아군이 폭발해 막대한 고정 피해를 입힙니다." },
  { id: "s50", tier: "silver", icon: "💡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/lightemup_small.png", name: "불을 밝혀", desc: "4번째 기본 공격마다 적중 시 추가 마법 피해를 입힙니다." },
  { id: "s51", tier: "silver", icon: "🦊", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/firfox_small.png", name: "불여우", desc: "자동 사용, 이동 속도가 증가하고 주위를 빙빙 도는 불꽃 3개를 생성합니다." },
  { id: "s52", tier: "silver", icon: "📈", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/stats_small.png", name: "능력치!", desc: "능력치 모루를 2개 획득합니다." },
  { id: "s53", tier: "silver", icon: "🏁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "출발할 시간", desc: "사용 시 지속시간 동안 이동 속도가 증가합니다." },
  { id: "s54", tier: "silver", icon: "✅", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/killsecure_small.png", name: "확보된 킬", desc: "체력이 낮은 적에게 접근 시 이동 속도가 증가합니다." },
  { id: "s55", tier: "silver", icon: "👁️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "적응형 와드", desc: "스킬로 적 챔피언을 타격하면 대상의 피해 유형에 따라 잠시 방어력 또는 마법 저항력을 얻습니다." },
  { id: "s56", tier: "silver", icon: "🗡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "믿음직한 무기", desc: "스킬로 적 챔피언을 타격하면 우정의 결속이 형성됩니다. 우정 레벨에 따라 피해량이 일시적으로 증가합니다." },
  { id: "s57", tier: "silver", icon: "🛡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/mightyshield_small.png", name: "강력한 방패", desc: "보호막을 얻으면 초 동안 의 적응형 능력치를 얻습니다. (재사용 대기시간 초)" },
  { id: "s58", tier: "silver", icon: "⛰️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/mountainsoul_small.png", name: "대지의 영혼", desc: "전투에서 벗어나면 잠시 동안 보호막을 획득하는 대지의 영혼을 얻습니다." },
  { id: "s59", tier: "silver", icon: "💥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/flashbang_small.png", name: "점멸탄", desc: "점멸 사용 시 주변에 폭발을 일으켜 적중당한 적에게 마법 피해를 입히고 둔화시킵니다." },
  { id: "s60", tier: "silver", icon: "👻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/poltergeist_small.png", name: "폴터가이스트", desc: "폴터가이스트 소환사 주문을 얻습니다. 폴터가이스트는 방어막과 유체화를 동시에 사용합니다." },
  { id: "s61", tier: "silver", icon: "☃️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/snowday_small.png", name: "눈 오는 날", desc: "세트 보너스 눈덩이 증강의 스킬 가속 및 피해량이 증가합니다." },
  { id: "s62", tier: "silver", icon: "✨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/flash2_small.png", name: "점멸 2", desc: "두 번째 점멸 소환사 주문을 얻고 소환사 주문 가속이 증가합니다." },
  { id: "s63", tier: "silver", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/youspinmerightround_small.png", name: "빙글빙글", desc: "소환사 주문이 영웅의 비상으로 변경됩니다. 영웅의 비상을 사용하면 갈고리총을 발사해 지형에 고정시키며, 이후 스킬을 재사용하면 갈고리에 매달려 이동합니다." },
  { id: "s66", tier: "silver", icon: "🛡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/questsupportmain_small.png", name: "서포터 주력", desc: "퀘스트: 아군 챔피언의 체력을 회복시켜야 합니다. 보상: 이제 내 모든 체력 회복 효과가 최초 체력 회복 후 추가로 지속 체력 회복 효과를 부여합니다." },
  { id: "s68", tier: "silver", icon: "💣", iconUrl: "https://raw.communitydragon.org/latest/game/assets/maps/particles/kiwi/selfdestruct_small.png", name: "자폭", desc: "13초마다 자동 사용으로 자신에게 폭탄을 부착합니다. 폭탄은 폭발 시 주변 적에게 막대한 고정 피해를 입히고 공중으로 띄워 올립니다." },
  { id: "s69", tier: "silver", icon: "😈", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/speeddemon_small.png", name: "질주하는 악마", desc: "적 챔피언에게 스킬로 피해를 입히면 이동 속도가 증가합니다." },
  { id: "s74", tier: "silver", icon: "👁️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/poltergeist_small.png", name: "감시의 장막", desc: "초마다 적의 다음 스킬을 막아 주는 주문 방어막을 생성합니다." },
  { id: "s75", tier: "silver", icon: "➕", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_silver.png", name: "보강", desc: "스킬로 부여되는 보호막이 더 강력해지며, 효과가 대상이 잃은 체력에 비례합니다." },
  { id: "s76", tier: "silver", icon: "🔁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/transmutegold_small.png", name: "전환: 골드", desc: "무작위 골드 증강을 획득합니다.", special: "transmute", transmuteTier: "gold" },
  // ── 골드 (Gold) ── 개성이 뚜렷한 패시브형 증강
  { id: "g01", tier: "gold", icon: "🗡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradeie_small.png", name: "무한의 대검 업그레이드", desc: "500골드를 얻습니다. 무한의 대검을 보유하고 있으면 치명타 확률에 비례해 기본 공격 시 무작위로 치명타 피해량을 부여합니다." },
  { id: "g02", tier: "gold", icon: "🎯", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/criticalmissile_small.png", name: "치명적 미사일", desc: "치명타 적중 시 미사일을 발사해 마법 피해를 입힙니다. 치명타 확률이 증가합니다." },
  { id: "g03", tier: "gold", icon: "😤", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/aram_phenomenalevil_small.png", name: "극악무도", desc: "적을 스킬로 맞히면 영구적으로 1의 주문력을 얻습니다. 4라운드 이후 이 증강을 선택할 경우 40의 주문력을 얻습니다." },
  { id: "g04", tier: "gold", icon: "🔭", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/skilledsniper_small.png", name: "노련한 저격수", desc: "멀리 떨어진 적에게 궁극기 이외의 스킬을 적중시키면 해당 스킬의 재사용 대기시간이 대폭 감소합니다." },
  { id: "g05", tier: "gold", icon: "⚡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/lightningstrikes_small.png", name: "벼락", desc: "총 공격 속도가 20% 증가합니다. 초당 공격 횟수 3.5회에서 적중 시 추가 마법 피해를 입힙니다." },
  { id: "g07", tier: "gold", icon: "🩸", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/soulsiphon_small.png", name: "영혼 흡수", desc: "치명타로 입힌 피해량의 10%만큼 체력을 회복합니다. 치명타 확률이 25% 증가합니다." },
  { id: "g08", tier: "gold", icon: "💗", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/perseverance_small.png", name: "인내심", desc: "체력 재생 효과가 크게 증가하고 체력이 낮으면 추가로 증가합니다." },
  { id: "g09", tier: "gold", icon: "⚔️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/spiritualpurification_small.png", name: "처형자", desc: "체력이 40% 아래로 떨어진 적에게 입히는 피해량이 10% 증가합니다. 처치 관여 시 기본 스킬이 초기화됩니다." },
  { id: "g10", tier: "gold", icon: "🔧", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/apexinventor_small.png", name: "최첨단 발명가", desc: "아이템 가속이 100 증가합니다. (50%의 아이템 재사용 대기시간 감소 효과와 동일) 아이템 가속은 모든 아이템 스킬의 재사용 대기시간을 감소시킵니다." },
  { id: "g11", tier: "gold", icon: "🥁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/criticalrhythm_small.png", name: "치명적 리듬", desc: "기본 공격 시 치명타가 발동하면 공격 속도 중첩을 획득합니다. 치명타 확률을 얻습니다." },
  { id: "g12", tier: "gold", icon: "🛡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/quest_steelyourheart_small.png", name: "퀘스트: 강철 같은 심장", desc: "조건: 효과가 400중첩 이상 적용된 강철심장을 보유해야 합니다. 보상: 강철심장 중첩이 3배가 됩니다. 체력 재생이 강철심장 중첩의 12.5%만큼 증가합니다." },
  { id: "g13", tier: "prism", icon: "🎰", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dualwield_small.png", name: "한 발에 두 놈", desc: "미스 포츈이 하나의 대상에게 총알을 쏘아 대상과 대상 뒤에 있는 적에게 피해를 입힙니다." },
  { id: "g14", tier: "gold", icon: "👻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/etherealweapon_small.png", name: "환영 무기", desc: "스킬 사용 시 적중 시 효과를 적용합니다." },
  { id: "g15", tier: "gold", icon: "🧛", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/vampired_small.png", name: "흡혈병", desc: "아군이 자신의 체력을 회복시키거나 자신이 체력 재생을 얻을 수 없습니다. 모든 피해 흡혈 효과를 얻습니다." },
  { id: "g16", tier: "gold", icon: "✨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradesheen_small.png", name: "광휘의 검 업그레이드", desc: "주문 검 효과가 추가 피해를 입히고 대상 체력의 일정 비율만큼 자신의 체력을 회복시킵니다. 추가로 250골드를 획득합니다." },
  { id: "g17", tier: "gold", icon: "🌱", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/growthspurt_small.png", name: "급속 성장", desc: "급속 성장 소환사 주문을 얻습니다. 급속 성장으로 급격히 크기가 커져 주변 적을 공중으로 띄워 올리고, 최대 체력을 얻습니다." },
  { id: "g18", tier: "gold", icon: "❄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/snowballupgrade_small.png", name: "눈덩이 업그레이드", desc: "눈덩이의 스킬 가속이 증가합니다. 적에게 눈덩이가 적중하면 눈이 내려 주변 적에게 광역 피해를 입히고 둔화시킵니다. 눈덩이를 보유하지 않은 경우 눈덩이를 얻습니다." },
  { id: "g19", tier: "gold", icon: "🔄", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/recursion_small.png", name: "되풀이", desc: "스킬 가속이 40 증가합니다." },
  { id: "g20", tier: "gold", icon: "🏹", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/marksmage_small.png", name: "마법 명사수", desc: "기본 공격 시 주문력의 75%만큼 추가 물리 피해를 입힙니다." },
  { id: "g21", tier: "gold", icon: "🚀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/maps/particles/kiwi/magicmissile_small.png", name: "마법 미사일", desc: "스킬로 피해를 입히면 마법 탄환 3발을 발사해 각각 최대 체력에 비례하는 고정 피해를 입힙니다." },
  { id: "g22", tier: "gold", icon: "🏃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/outlawsgrit_small.png", name: "무법자의 투지", desc: "돌진, 점멸, 순간이동 스킬을 사용한 후 방어력 및 마법 저항력을 얻습니다." },
  { id: "g23", tier: "gold", icon: "🌊", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/overflow_small.png", name: "범람", desc: "마나 소모량이 2배가 됩니다. 스킬의 체력 회복량, 보호막 흡수량 및 피해량이 최대 마나에 비례해 증가합니다." },
  { id: "g24", tier: "gold", icon: "🎵", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/sonata_small.png", name: "소나타", desc: "일정 주기마다 인내의 아리아와 기민함의 노래를 번갈아 자동 사용합니다. 인내의 아리아는 주변 아군의 체력을 회복시키고 일시적으로 보호막 오라를 부여합니다. 기민함의 노래는 추가 이동 속도를 부여하는 오라를 잠시 동안 생성합니다." },
  { id: "g25", tier: "gold", icon: "🌾", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/frombeginningtoend_small.png", name: "시작부터 끝까지", desc: "선제공격과 어둠의 수확 핵심 룬을 얻습니다." },
  { id: "g26", tier: "gold", icon: "🎉", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/getexcited_small.png", name: "신난다!", desc: "적 챔피언이나 에픽 정글 몬스터 처치에 관여하거나 구조물 파괴를 도우면 이동 속도와 공격 속도가 대폭 상승합니다." },
  { id: "g27", tier: "gold", icon: "💥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/spiritualpurification_small.png", name: "영혼의 정화", desc: "처치 시 적의 시체를 정화해 아군이 영혼의 꽃잎을 획득합니다. 이후 주변 적을 잠시 둔화시키고 현재 체력에 비례한 적응형 피해를 입힙니다." },
  { id: "g28", tier: "gold", icon: "👑", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradehubris_small.png", name: "오만 업그레이드", desc: "처치 관여 시, 오만이 체력을 회복시키고 이동 속도를 부여합니다. 두 효과 모두 명성 중첩에 비례하여 증가합니다. 추가로 250골드를 획득합니다." },
  { id: "g30", tier: "gold", icon: "⏱️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/itskillingtime_small.png", name: "처형 시간", desc: "궁극기 사용 후 모든 적 챔피언에게 죽음의 표식을 남깁니다. 표식이 있는 동안 적에게 입힌 피해를 비축합니다. 표식의 효과가 끝날 때 폭발해 비축된 피해를 입힙니다." },
  { id: "g31", tier: "gold", icon: "👼", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/celestialbody_small.png", name: "천상의 신체", desc: "1000의 체력을 얻지만, 피해량이 10% 감소합니다." },
  { id: "g32", tier: "gold", icon: "🐢", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/slowandsteady_small.png", name: "천천히 꾸준히", desc: "공격 속도는 일정 수치보다 높아질 수 없습니다. 모든 추가 공격 속도가 공격력으로 전환됩니다." },
  { id: "g34", tier: "gold", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/shrinkengine_small.png", name: "축소 엔진", desc: "처치 관여 시 크기가 작아지고 스킬 가속 및 이동 속도를 얻습니다. 사망 시 중첩 일부를 잃습니다." },
  { id: "g35", tier: "gold", icon: "💢", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/vulnerability_small.png", name: "취약", desc: "아이템 및 지속 피해 효과에 치명타가 적용될 수 있습니다. 치명타 확률이 25% 증가합니다." },
  { id: "g36", tier: "gold", icon: "💖", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/criticalhealing_small.png", name: "치명적 치유", desc: "체력 회복 및 보호막 효과에 치명타가 적용되어 증가합니다. 치명타 확률이 25% 증가합니다." },
  { id: "g37", tier: "gold", icon: "🎯", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/itscritical_small.png", name: "치명적인 공격", desc: "치명타 확률이 50% 증가합니다." },
  { id: "g38", tier: "gold", icon: "🦾", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/tank_engine_small.png", name: "탱크 엔진", desc: "처치 관여마다 크기가 커지고 일정 비율의 추가 체력을 얻습니다." },
  { id: "g40", tier: "gold", icon: "✌️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/twicethrice_small.png", name: "두 배 세 배", desc: "3번째 기본 공격을 가할 때마다 적중 시 효과가 한 번 더 발동합니다." },
  { id: "g42", tier: "gold", icon: "🔫", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/scopierweapons_small.png", name: "상급 조준경 부착", desc: "공격 사거리가 증가합니다." },
  { id: "g44", tier: "gold", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/bigbrain_small.png", name: "전술적 대비", desc: "각 라운드 시작 시 주문력에 비례해 피해를 흡수하는 보호막을 얻습니다." },

  { id: "g45", tier: "gold", icon: "💰", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/bloodmoney2_small.png", name: "타오르는 이자", desc: "챔피언에게 적용한 화상 및 지속 피해 효과가 골드를 생성합니다." },
  { id: "g46", tier: "gold", icon: "🧃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/warlockjuicebox_small.png", name: "마도사의 주스 상자", desc: "모든 피해 흡혈을 얻습니다." },
  { id: "g47", tier: "gold", icon: "🦷", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/questburstingteeth_small.png", name: "이빨 요정", desc: "적에게 폭발적 피해를 입히면 이빨을 떨어뜨립니다. 이빨을 주우면 영구적으로 물리 관통력과 마법 관통력을 얻습니다." },
  { id: "g48", tier: "gold", icon: "🎗️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/donation_small.png", name: "후원", desc: "골드를 획득합니다. 묻지도 따지지도 않습니다." },
  { id: "g49", tier: "gold", icon: "🚨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/weewooweewoo_small.png", name: "삐뽀삐뽀", desc: "체력이 낮은 아군을 향해 이동할 때 이동 속도가 증가합니다. 대상의 체력이 낮을수록 체력 회복량 및 보호막 흡수량이 증가합니다." },
  { id: "g50", tier: "gold", icon: "➕", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/statsonstats_small.png", name: "능력치 더하기 능력치!", desc: "능력치 모루를 3개 획득합니다." },
  { id: "g51", tier: "gold", icon: "🏀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/questbangbang_small.png", name: "로켓 배송", desc: "퀘스트: 스킬로 적 챔피언을 저격해야 합니다. 보상: 저격한 적 챔피언에게 유성을 날려 주변 지역에 마법 피해를 입힙니다." },
  { id: "g52", tier: "gold", icon: "⏱️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/withhaste_small.png", name: "속행", desc: "스킬 가속의 120%에 해당하는 이동 속도를 얻습니다." },
  { id: "g53", tier: "gold", icon: "☠️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/endlessdecimate_small.png", name: "끝없는 학살", desc: "전투 중 자동 사용으로 도끼를 원형으로 휘둘러 물리 피해를 입힙니다. 바깥쪽 칼날에 적 적중 시 추가 피해를 입히고 체력을 회복합니다." },
  { id: "g54", tier: "gold", icon: "🍞", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "빵과 버터", desc: "스킬 가속을 100 얻습니다." },
  { id: "g55", tier: "gold", icon: "🏎️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "가속 추구", desc: "퀘스트: 스킬로 적 챔피언을 맞혀야 합니다. 보상: 퀘스트 레벨당 스킬 가속이 증가합니다. (최대치 있음)" },
  { id: "g56", tier: "gold", icon: "🔨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/bonk_large.png", name: "꽁!", desc: "강화된 기본 공격과 스킬이 대상 및 주변 적에게 추가로 피해를 입힙니다." },
  { id: "g57", tier: "gold", icon: "⛰️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/lightningstrikes_small.png", name: "지형 생성됨", desc: "스킬이 주변 지역에 피해를 입힙니다." },
  { id: "g58", tier: "gold", icon: "🧀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "빵과 치즈", desc: "스킬 가속을 100 얻습니다." },
  { id: "g59", tier: "gold", icon: "🪡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/threadtheneedle_small.png", name: "바늘에 실 끼우기", desc: "방어구 관통력 및 마법 관통력 15%를 얻습니다." },
  { id: "g60", tier: "gold", icon: "⛓️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradehubris_small.png", name: "굶주린 속박", desc: "스킬로 적 챔피언을 이동 불가 상태로 만들거나 이동 스킬을 사용할 수 없게 하면 추가 피해를 입히고 체력을 회복합니다." },
  { id: "g61", tier: "gold", icon: "💪", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/marksmage_small.png", name: "위력 추구", desc: "퀘스트: 스킬로 적 챔피언을 맞혀야 합니다. 보상: 피해량이 영구적으로 증가합니다." },
  { id: "g62", tier: "gold", icon: "🌅", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dawnbringersresolve_small.png", name: "빛의 인도자 결의", desc: "체력이 60% 아래로 떨어지면 3초 동안 체력을 회복합니다." },
  { id: "g63", tier: "gold", icon: "🐣", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "작은 도움", desc: "지속시간 동안 공격 사거리와 공격 속도가 증가합니다." },
  { id: "g64", tier: "gold", icon: "🪃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/okboomerang_small.png", name: "부메랑 투척", desc: "자동 사용, 7초마다 근처 적에게 부메랑을 던집니다." },
  { id: "g65", tier: "gold", icon: "🍲", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/questpressurecooker_small.png", name: "압력솥", desc: "매초 최대 체력에 비례해 주변 적 챔피언에게 중첩되는 화상 효과를 적용합니다. 퀘스트: 적 챔피언에게 화상 피해를 입혀야 합니다. 보상: 퀘스트 레벨당 크기와 피해량이 증가합니다." },
  { id: "g66", tier: "gold", icon: "🏃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/overextender_small.png", name: "무리한 진입", desc: "귀환하여 대포 발사기에 탑승하세요. 발사기의 사거리, 이동 속도, 피해량이 대폭 증가했습니다." },
  { id: "g67", tier: "gold", icon: "🔥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/firebrand_small.png", name: "화염 낙인", desc: "기본 공격 시 무한히 중첩되는 화상(적중 시) 효과를 적용해 지속적으로 피해를 입힙니다." },
  { id: "g68", tier: "gold", icon: "👻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/souleater_small.png", name: "영혼의 포식자", desc: "나서스는 적의 영혼을 흡수하여 추가 생명력 흡수 효과를 얻습니다." },
  { id: "g69", tier: "gold", icon: "🎁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/allforyou_small.png", name: "너만을 위해", desc: "아군에게 사용하는 체력 회복 및 보호막 효과가 증가합니다." },
  { id: "g70", tier: "gold", icon: "🪙", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/youchmycoins_small.png", name: "으악, 내 동전!", desc: "처치 관여 시 적 챔피언이 주변에 자신과 아군이 주울 수 있는 동전을 떨어뜨립니다. 각 동전은 골드의 가치를 지닙니다." },
  { id: "g71", tier: "gold", icon: "🍓", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "빵과 잼", desc: "스킬 가속을 100 얻습니다." },
  { id: "g72", tier: "gold", icon: "🌄", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/searingdawn_small.png", name: "타오르는 새벽", desc: "스킬이 적에게 표식을 남깁니다. 적은 아군의 다음 기본 공격 또는 스킬로부터 마법 피해를 추가로 입습니다." },
  { id: "g73", tier: "gold", icon: "🧟", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/minionmancer_small.png", name: "소환술사", desc: "소환물의 크기, 체력, 피해량이 35% 증가합니다." },
  { id: "g74", tier: "gold", icon: "🌙", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/nightstalking_small.png", name: "밤의 추적", desc: "자신이 피해를 입힌 챔피언이 잠시 안에 죽으면 이동 속도가 증가하고 투명 상태가 됩니다." },
  { id: "g75", tier: "gold", icon: "🙏", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/slowactingpainkillers_small.png", name: "신성한 중재", desc: "전투 시작 직후 보호의 별을 소환합니다. 별이 착지하면 자신과 주변 아군이 잠시 무적 상태가 됩니다. 이후 25초마다 자동 사용합니다." },
  { id: "g76", tier: "gold", icon: "🦈", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/fishbait_small.png", name: "상어 미끼", desc: "사망 몇 초 후 상어가 주변 모든 적을 물어뜯습니다. 사망 후에도 이동하여 상어 공격의 대상을 정할 수 있습니다." },
  { id: "g77", tier: "gold", icon: "⚔️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "자비의 일격", desc: "스킬로 아군의 체력을 회복시키거나 보호막을 부여하면 다음 기본 공격 시 공격 사거리와 공격 속도가 증가하고 추가로 최대 체력 비례 마법 피해를 입힙니다." },
  { id: "g78", tier: "gold", icon: "🔫", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/shrinkray_small.png", name: "감쇠 광선", desc: "기본 공격 시 대상이 입히는 피해량과 크기를 10% 감소시킵니다. (적중 시)" },
  { id: "g79", tier: "gold", icon: "🌿", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/natureishealing_small.png", name: "자연의 회복", desc: "수풀에 들어가면 대량의 체력을 회복합니다." },
  { id: "g80", tier: "gold", icon: "🤝", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/patontheback_small.png", name: "격려하기", desc: "근처를 지나가는 아군이 격려하며 보호막과 이동 속도를 부여합니다." },
  { id: "g81", tier: "gold", icon: "🧱", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/impassable_small.png", name: "넘을 수 없는 벽", desc: "여진과 빙결 강화 핵심 룬을 얻습니다." },
  { id: "g82", tier: "gold", icon: "🥾", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "날쌘걸음", desc: "사용 시 커서 방향으로 돌진합니다." },
  { id: "g83", tier: "gold", icon: "🦔", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/pincushion_small.png", name: "고슴도치", desc: "챔피언에게 피해를 입으면 바늘 폭발이 축적되며, 이후 바늘이 튀어 나가 주변 적에게 피해를 입히고 둔화시킵니다." },
  { id: "g84", tier: "gold", icon: "🦈", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/sharktempest_small.png", name: "상어 폭풍", desc: "상어가 눈덩이 주위를 돌며 주변 적을 둔화시키고 피해를 입힙니다. 눈덩이가 챔피언에게 적중하면 해당 챔피언이 상어 폭풍에 갇힙니다!" },
  { id: "g85", tier: "gold", icon: "🎱", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/pinballsnowball_small.png", name: "핀볼", desc: "눈덩이의 스킬 가속이 증가하고 추가 고정 피해를 입힙니다. 눈덩이가 벽에 튕기면 크기와 피해량이 증가하고 재사용 대기시간이 감소합니다." },
  { id: "g87", tier: "gold", icon: "🌳", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/brushpower_small.png", name: "Hide on bush", desc: "수풀에 들어간 후 잠시 동안 피해량이 증가합니다. 수풀에 머무르면 효과가 초기화됩니다." },
  { id: "g88", tier: "gold", icon: "💞", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/equillibrium_small.png", name: "우리의 치유", desc: "주변의 누군가가 체력을 회복할 때마다 그 회복량 일부만큼 자신의 체력을 회복합니다. 적의 체력 회복 효과는 두 배로 적용됩니다." },
  { id: "g89", tier: "gold", icon: "💥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "연쇄 반응", desc: "스킬로 뒤로 밀어낸 대상이 다른 챔피언과 부딪히면 둘 다 공중에 뜨고 피해를 입습니다. 지형에 충돌하면 공중에 뜨는 시간이 길어지고 추가 피해를 입습니다." },
  { id: "g90", tier: "gold", icon: "❄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/snowbomb_small.png", name: "눈 폭발", desc: "눈덩이를 다시 사용하면 증가한 피해를 입히고 대상을 공중에 띄우며, 주변 적들을 뒤로 밀어냅니다." },
  { id: "g92", tier: "gold", icon: "🌶️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/grandmaschilioil_small.png", name: "할머니의 고추기름", desc: "적에게 기본 공격 및 스킬 적중 시 화상을 적용하고, 주변에 고추기름 웅덩이를 생성합니다. 고추기름은 체력을 회복시키고 적에게 화상을 적용합니다. 고추기름의 효과는 적용한 화상의 수에 비례해 강력해집니다." },
  { id: "g93", tier: "gold", icon: "🔑", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/keystoneconjurer_small.png", name: "핵심 룬 요술사", desc: "콩콩이 소환과 신비로운 유성 핵심 룬을 얻습니다." },
  { id: "g95", tier: "gold", icon: "🌿", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/rabblerousing_small.png", name: "원기 회복", desc: "스킬 사용 시 체력을 회복합니다." },
  { id: "g98", tier: "gold", icon: "🌀", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_gold.png", name: "공허 돌진", desc: "스킬로 돌진 시 적 챔피언을 둔화시키고 마법 피해를 입히는 공허 지대를 생성합니다." },
  { id: "g99", tier: "gold", icon: "🗡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradeie_small.png", name: "갈라진 하늘 업그레이드", desc: "갈라진 하늘의 대상별 재사용 대기시간이 감소하고 잃은 체력의 일부만큼 체력을 회복합니다. 골드를 획득합니다." },
  { id: "g101", tier: "gold", icon: "🩸", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgradesheen_small.png", name: "굶주린 히드라 업그레이드", desc: "적에게 스킬 적중 시 쪼개기 효과가 발동됩니다. 굶주린 히드라의 생명력 흡수가 증가합니다. 골드를 획득합니다." },
  { id: "g102", tier: "gold", icon: "✨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/flashy_small.png", name: "점멸 난사", desc: "점멸 사용 가능 횟수가 1번 늘고, 재사용 대기시간이 2초가 됩니다." },
  { id: "g103", tier: "gold", icon: "🔮", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/transmuteprismatic_small.png", name: "전환: 프리즘", desc: "무작위 프리즘 증강을 획득합니다.", special: "transmute", transmuteTier: "prism" },
  // ── 프리즘 (Prism) ── 빌드를 뒤바꾸는 강력한 증강
  { id: "p01", tier: "prism", icon: "🦣", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/giantslayer_small.png", name: "거인 학살자", desc: "크기가 작아져 이동 속도가 증가하며 상대가 자신보다 큰 정도에 비례해 챔피언에게 추가 피해를 입힙니다." },
  { id: "p02", tier: "prism", icon: "💎", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/jeweledgauntlet_small.png", name: "보석 건틀릿", desc: "스킬에 치명타가 적용될 수 있습니다. 치명타 확률이 증가합니다." },
  { id: "p03", tier: "prism", icon: "👊", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/mysticpunch_small.png", name: "신비한 주먹", desc: "적중 시 스킬의 재사용 대기시간이 1.25초 감소합니다." },
  { id: "p04", tier: "prism", icon: "🙌", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dualwield_small.png", name: "양손잡이", desc: "기본 공격 시 투사체를 발사하고 총 공격 속도가 15% 증가합니다." },
  { id: "p05", tier: "prism", icon: "💡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/eureka_small.png", name: "유레카", desc: "주문력의 20%에 해당하는 스킬 가속을 얻습니다." },
  { id: "p06", tier: "prism", icon: "🗿", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/goliath_small.png", name: "거인", desc: "크기가 커져 체력이 15% 증가하고 적응형 능력치가 10% 증가합니다." },
  { id: "p07", tier: "prism", icon: "⚔️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/drawyoursword_small.png", name: "검을 뽑아라", desc: "이제 근접 챔피언으로 간주됩니다. 잃은 공격 사거리에 비례해 공격력, 체력, 공격 속도, 생명력 흡수 효과, 이동 속도를 얻습니다." },
  { id: "p08", tier: "prism", icon: "🎭", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/clowncollege_small.png", name: "광대 대학", desc: "속임수 소환사 주문을 얻습니다. 속임수를 사용하면 근처로 순간이동해 투명 상태가 됩니다." },
  { id: "p09", tier: "prism", icon: "♻️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/ultimaterevolution_small.png", name: "궁극기 대변혁", desc: "라운드마다 한 번 궁극기를 사용한 다음 초기화합니다." },
  { id: "p10", tier: "prism", icon: "🌟", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/zerohour_small.png", name: "궁극의 각성", desc: "궁극기 가속이 증가합니다. 궁극기 사용 시 기본 스킬이 초기화되고 잠시 동안 기본 스킬 가속이 증가합니다." },
  { id: "p12", tier: "prism", icon: "🥾", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/dropkick_small.png", name: "드롭킥", desc: "기본 공격 및 스킬이 체력이 낮은 적 챔피언을 처형하고, 뒤로 밀어내 폭발시키며 자신의 체력을 회복합니다." },
  { id: "p13", tier: "prism", icon: "♾️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/infiniterecursion_small.png", name: "무한 반복", desc: "스킬 가속을 처치 관여당 얻습니다." },
  { id: "p14", tier: "prism", icon: "🎻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/symphonyofwar_small.png", name: "전장의 교향곡", desc: "치명적 속도와 정복자 핵심 룬을 얻습니다." },
  { id: "p15", tier: "prism", icon: "🎩", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/quest_woogletswitchcap_small.png", name: "퀘스트: 우글렛의 마녀 모자", desc: "즉시 쓸데없이 큰 지팡이를 획득합니다. 라바돈의 죽음모자와 존야의 모래시계를 보유해야 합니다." },
  { id: "p16", tier: "prism", icon: "🥄", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/quest_urfschampion_small.png", name: "퀘스트: 우르프의 챔피언", desc: "조건은 처치에 10회 관여해야 합니다. 보상은 황금 뒤집개입니다." },
  { id: "p18", tier: "prism", icon: "🗿", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/courageofthecolossus_small.png", name: "거석상의 용기", desc: "적 챔피언을 이동 불가 상태로 만들거나 이동 스킬을 사용할 수 없게 하면 보호막을 얻습니다." },
  { id: "p19", tier: "prism", icon: "💃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/bladewaltz_small.png", name: "검무", desc: "검무 소환사 주문을 얻습니다. 검무를 사용하면 적에게 돌진해 6회 공격하는 동안 대상으로 지정되지 않습니다." },
  { id: "p21", tier: "prism", icon: "📜", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/backtobasics_small.png", name: "기본으로 돌아가기", desc: "스킬 피해량, 체력 회복량, 보호막 흡수량 및 스킬 가속이 증가하지만 궁극기를 사용할 수 없습니다." },
  { id: "p22", tier: "prism", icon: "👑", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/kingme_small.png", name: "나는 왕이다", desc: "전설급 아이템을 소지하고 처음으로 적 이동 수단을 사용하면 왕이 되어 아이템이 업그레이드되며, 무작위 프리즘 증강을 얻습니다." },
  { id: "p23", tier: "prism", icon: "🛡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/canttouchthis_small.png", name: "난공불락", desc: "궁극기를 사용하면 잠시 동안 무적 상태가 됩니다." },
  { id: "p25", tier: "prism", icon: "❄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/biggestsnowballever_small.png", name: "데굴데굴 눈덩이", desc: "눈덩이의 스킬 가속이 증가합니다. 눈덩이가 거대해지고 미니언을 관통합니다." },
  { id: "p26", tier: "prism", icon: "🏃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dashing_small.png", name: "돌진", desc: "돌진, 도약, 점멸, 순간이동 스킬의 스킬 가속이 75만큼 증가합니다." },
  { id: "p27", tier: "prism", icon: "🧟", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/madscientist_small.png", name: "미친 과학자", desc: "라운드마다 크기가 커져 적응형 능력치 및 체력이 증가하거나 크기가 작아져 스킬 가속 및 이동 속도가 증가합니다." },
  { id: "p28", tier: "prism", icon: "🙏", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/empoweredbythefaithful_small.png", name: "신념을 통한 강화", desc: "아군을 상대로 체력을 회복시키거나 보호막을 씌우면 대상을 축복합니다." },
  { id: "p31", tier: "prism", icon: "🩸", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/glasscannon_small.png", name: "유리 대포", desc: "최대 체력이 감소하며 피해량에 비례한 추가 고정 피해를 입힙니다." },
  { id: "p32", tier: "prism", icon: "☄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/cruelty_small.png", name: "잔혹 행위", desc: "이동 불가 또는 속박 상태가 되면 대상 위로 혜성을 소환합니다." },
  { id: "p35", tier: "prism", icon: "🔄", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/circleofdeath_small.png", name: "죽음의 순환", desc: "체력을 회복하거나 체력을 재생하면 가장 가까운 적 챔피언에게 마법 피해를 입힙니다." },
  { id: "p36", tier: "prism", icon: "😎", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/madscientist_small.png", name: "지옥불 난사 발동", desc: "무모한 충동을 얻습니다. 스타일이 S등급에 도달하면 지옥불 난사를 자동 사용합니다." },
  { id: "p37", tier: "prism", icon: "🔗", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/infernalconduit_small.png", name: "지옥의 전도체", desc: "스킬 사용 시 무한히 중첩되는 화상 효과를 적용합니다." },
  { id: "p38", tier: "prism", icon: "🍲", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/slowcooker_small.png", name: "찜솥", desc: "매초 최대 체력에 비례해 주변 적에게 무한히 중첩되는 화상 효과를 적용합니다." },
  { id: "p39", tier: "prism", icon: "🕊️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/empyreampromise_small.png", name: "창공의 서약", desc: "사용하면 아군에게 돌진하고 도착 시 자신과 아군 모두 보호막을 얻습니다." },
  { id: "p40", tier: "prism", icon: "🔭", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/scopiestweapons_small.png", name: "최상급 조준경 부착", desc: "공격 사거리가 증가합니다." },
  { id: "p41", tier: "prism", icon: "🏆", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/finalform_small.png", name: "최종 형태", desc: "궁극기를 사용하면 잠시 동안 보호막, 모든 피해 흡혈, 이동 속도를 얻습니다." },
  { id: "p45", tier: "prism", icon: "💋", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/promqueen_small.png", name: "퀸카", desc: "일정 주기마다 반짝이는 티아라를 자동 사용합니다. 티아라를 쓰면 라칸의 궁극기를 얻어 닿는 적을 매혹합니다." },
  { id: "p46", tier: "prism", icon: "🔫", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/fanthehammer_small.png", name: "탄환 세례", desc: "기본 공격 시 탄환을 5개 발사합니다." },
  { id: "p47", tier: "prism", icon: "💃", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/tapdancer_small.png", name: "탭 댄서", desc: "기본 공격 시 이동 속도를 얻습니다. 이동 속도의 10%에 해당하는 공격 속도를 얻습니다." },
  { id: "p48", tier: "prism", icon: "🎁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/pandoras_box_small.png", name: "판도라의 상자", desc: "모든 증강을 무작위 프리즘 증강으로 전환합니다.", special: "pandora" },
  { id: "p50", tier: "prism", icon: "🥤", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/proteinshake_small.png", name: "프로틴 음료", desc: "추가 방어력 및 마법 저항력에 비례하여 체력 회복 및 보호막 효과를 얻습니다." },
  { id: "p52", tier: "prism", icon: "🤺", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/masterofduality_small.png", name: "결투의 대가", desc: "라운드가 끝날 때까지, 기본 공격 시 주문력을, 스킬 사용 시 공격력을 얻습니다." },
  { id: "p53", tier: "prism", icon: "🚷", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/stuckinherewithme_small.png", name: "도망갈 수 없어", desc: "궁극기를 사용하면 주변 적을 도발하고 피해량 감소를 얻습니다." },
  { id: "p55", tier: "prism", icon: "🐉", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/ultrahydra_small.png", name: "궁극의 히드라", desc: "활성화 시 모든 히드라 아이템의 사용 시 효과가 발동됩니다." },
  { id: "p56", tier: "prism", icon: "🕊️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/glasscannon_small.png", name: "초월 의식", desc: "처치 관여 시 적 챔피언이 정수를 남깁니다. 정수를 공격하면 이동 속도가 증가합니다." },
  { id: "p57", tier: "prism", icon: "🎲", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/highroller_small.png", name: "도박꾼", desc: "주변 적이 죽을 때 일정 확률로 능력치 모루를 떨어뜨립니다." },
  { id: "p58", tier: "prism", icon: "🐻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/drop_bear_small.png", name: "곰 투하", desc: "사망 시, 플레이어의 증강을 모두 지닌 거대 티버가 하늘에서 떨어져 주변 적에게 피해를 입힙니다." },
  { id: "p59", tier: "prism", icon: "👹", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/handofbaron_small.png", name: "남작의 도움", desc: "적응형 능력치를 얻습니다. 주변 아군 미니언이 대폭 강화됩니다." },
  { id: "p60", tier: "prism", icon: "🕊️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/windspeakersblessing_small.png", name: "바람전달자의 축복", desc: "회복 및 보호막 효과를 부여하면 3초 동안 대상의 방어력 및 마법 저항력이 증가합니다." },
  { id: "p61", tier: "prism", icon: "👻", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/spiritbomb_small.png", name: "영혼 폭탄", desc: "아군 챔피언의 체력을 회복시키거나 보호막을 씌우면 영혼 폭탄이 중첩됩니다." },
  { id: "p62", tier: "prism", icon: "✨", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/omnisoul_small.png", name: "전능의 영혼", desc: "무작위 드래곤 영혼 2개를 획득합니다." },
  { id: "p63", tier: "prism", icon: "🧙", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/eureka_small.png", name: "대마법사", desc: "스킬을 사용하면 사용한 스킬 재사용 대기시간의 일부만큼 다른 무작위 스킬의 재사용 대기시간을 반환합니다." },
  { id: "p64", tier: "prism", icon: "♟️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/dashing_small.png", name: "앙파상", desc: "주기적으로 적 챔피언의 급소를 파악합니다. 급소를 기본 공격 또는 스킬로 타격하면 피해를 입히고, 체력을 회복하며, 이동 속도가 증가합니다." },
  { id: "p65", tier: "prism", icon: "💰", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/goldrend_small.png", name: "골드 강탈", desc: "기본 공격이나 스킬로 챔피언에게 피해를 입히면 추가 마법 피해를 입히고 골드를 획득하며 이동 속도가 증가합니다." },
  { id: "p66", tier: "prism", icon: "➕", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/statsonstatsonstats_small.png", name: "능력치 더하기 능력치 더하기 능력치!", desc: "능력치 모루를 4개 획득합니다." },
  { id: "p67", tier: "prism", icon: "🔁", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_prismatic.png", name: "메아리 시전", desc: "스킬을 사용하면 마우스 커서 위치로 분신을 보내고 스킬을 재사용합니다." },
  { id: "p68", tier: "prism", icon: "📜", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/wisdomofages_small.png", name: "불길한 서약", desc: "잃은 체력에 비례하여 주문력, 이동 속도, 모든 피해 흡혈을 얻지만, 스킬을 사용할 때마다 피해를 입습니다." },
  { id: "p69", tier: "prism", icon: "😤", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/hellbent_small.png", name: "열의", desc: "적 챔피언에게 기본 공격 또는 스킬로 피해를 입히면 중첩을 얻습니다." },
  { id: "p70", tier: "prism", icon: "🎯", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_prismatic.png", name: "3연발", desc: "스킬이 전방에 있는 적 2명을 추가로 대상 지정합니다." },
  { id: "p71", tier: "prism", icon: "⚡", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_prismatic.png", name: "과충전", desc: "다른 스킬 사용 시 재사용 대기시간이 초기화됩니다." },
  { id: "p72", tier: "prism", icon: "🔱", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_prismatic.png", name: "주문 분산", desc: "투사체가 적중하거나 최대 사거리에 도달하거나 재사용 시 두 개로 나뉩니다." },
  { id: "p73", tier: "prism", icon: "🧚", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/feymagic_small.png", name: "요정 마법", desc: "궁극기로 적에게 피해를 입히면 잠시 동안 변이시킵니다." },
  { id: "p74", tier: "prism", icon: "🗿", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/iamthejuggernaut_small.png", name: "거인의 결의", desc: "피해를 받거나 입히면 중첩을 얻습니다. 중첩마다 적응형 능력치, 방어력, 마법 저항력, 크기, 강인함을 얻습니다." },
  { id: "p75", tier: "prism", icon: "🖐️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/squishyslappygrab_small.png", name: "말랑 찰싹 손", desc: "때때로 주변 모든 적 챔피언에게 말랑 찰싹 손을 내보내 연결합니다." },
  { id: "p76", tier: "prism", icon: "❄️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/goldensnowball_small.png", name: "신성한 눈덩이", desc: "눈덩이의 스킬 가속이 증가합니다. 눈덩이로 돌진하면 잠시 무적 상태가 됩니다." },
  { id: "p77", tier: "prism", icon: "🏹", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/genericabilityaugmenticon_prismatic.png", name: "다중 공격", desc: "스킬을 사용할 때마다 투사체를 추가로 발사합니다." },
  { id: "p78", tier: "prism", icon: "📌", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/symphonyofwar_small.png", name: "바늘꽂이", desc: "지속시간 동안 기본 공격 시 대상에게 대못을 박습니다." },
  { id: "p79", tier: "prism", icon: "🌐", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/surgefield_small.png", name: "방출 역장", desc: "궁극기 사용 시 스킬 가속과 이동 속도를 부여하는 구역을 생성합니다." },
  { id: "p80", tier: "prism", icon: "🌌", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/whenthedarknesscomes_small.png", name: "차원 이동", desc: "어둠이 드리우면 소환사 주문을 얻습니다. 내부의 모든 대상을 다른 차원으로 이동시키는 영역을 생성합니다." },
  { id: "p81", tier: "prism", icon: "🐾", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/questporocharge_small.png", name: "포로 쇄도", desc: "포로 간식을 모아 포로 마리에게 줘야 합니다. 보상은 포로 돌격 소환사 주문입니다." },
  { id: "p86", tier: "prism", icon: "🤖", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/skipthebasic_small.png", name: "궁극기 봇", desc: "스킬 가속이 궁극기에만 적용되지만, 효과가 50% 증가합니다. 스킬 가속이 100 증가합니다." },
  { id: "p87", tier: "prism", icon: "🗡️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/upgrademikaelsblessing_small.png", name: "꽃피는 새벽의 검 업그레이드", desc: "공격 속도를 획득합니다. 적 챔피언 공격 시 체력 회복량이 증가합니다." },
  { id: "p88", tier: "prism", icon: "💣", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/earthwake_small.png", name: "대지의 각성", desc: "돌진, 점멸, 순간이동 스킬이 1초 후에 폭발하는 흔적을 남깁니다." },
  { id: "p89", tier: "prism", icon: "🔥", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/kiwi/augments/icons/quest_voidimmolation_small.png", name: "이케시아의 몰락", desc: "즉시 바미의 불씨를 획득합니다. 태양불꽃 방패와 공허한 광휘를 보유해야 합니다." },
  { id: "p90", tier: "prism", icon: "🌪️", iconUrl: "https://raw.communitydragon.org/latest/game/assets/ux/cherry/augments/icons/transmutechaos_small.png", name: "전환: 혼돈", desc: "무작위 증강 2개를 획득합니다." },
];

// 레벨(3/7/11/15)별로 실버/골드/프리즘 증강이 뽑힐 확률 가중치
window.LEVEL_TIER_WEIGHTS = {
  3: { silver: 70, gold: 30, prism: 0 },
  7: { silver: 40, gold: 50, prism: 10 },
  11: { silver: 15, gold: 55, prism: 30 },
  15: { silver: 5, gold: 40, prism: 55 },
};

window.TIER_META = {
  silver: {
    label: "실버", ring: "ring-slate-300", grad: "from-slate-500 to-slate-300", text: "text-slate-100", glow: "",
    border: "border-slate-600", accent: "text-slate-300",
    // 아이콘(대부분 흰색 실루엣)에 등급별 색을 입히는 CSS 필터
    iconFilter: "saturate(0.85) brightness(1.05)",
  },
  gold: {
    label: "골드", ring: "ring-amber-300", grad: "from-amber-600 to-yellow-300", text: "text-amber-50", glow: "shadow-[0_0_18px_rgba(250,204,21,0.45)]",
    border: "border-amber-500/70", accent: "text-amber-300",
    iconFilter: "sepia(0.75) saturate(3.5) hue-rotate(10deg) brightness(1.15)",
  },
  prism: {
    label: "프리즘", ring: "ring-fuchsia-300", grad: "from-fuchsia-500 via-purple-400 to-sky-300", text: "text-white", glow: "shadow-[0_0_24px_rgba(217,70,239,0.55)] animate-pulse",
    border: "border-fuchsia-400/70", accent: "text-fuchsia-200",
    iconFilter: "sepia(1) saturate(6) hue-rotate(220deg) brightness(1.15)",
  },
};
